# Generated by Django 4.1.1 on 2023-07-23 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='hire_data',
            new_name='hire_date',
        ),
    ]
